### ISSUE TITLE
Something called "ANDROID_HOST_OUT" is not working

### ISSUE THREAD

**Issue by sting8k** [Gyoonus/deoptfuscator#3]
I think there are still some modules required to run this tool

```
Traceback (most recent call last):
  File "deoptfuscator.py", line 19, in <module>
    deobfuscator.main(".apk/"+dex)
  File "deobfuscator/deobfuscator.py", line 9, in main
    ret = opaque_id.opaque_id(dex)
  File "deobfuscator/opaque_id.py", line 6, in opaque_id
    child = subprocess.Popen([os.getenv('ANDROID_HOST_OUT')+'/bin/OTest'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by Gyoonus** [comment]
you should launch this command 

 $. ./launch.sh
