### ISSUE TITLE
OTest File not found

### ISSUE THREAD

**Issue by h4ckd0tm3** [Gyoonus/deoptfuscator#4]
So... It says that it couldn't find OTest

```
I: Using Apktool 2.4.1 on XXXXXX
I: Copying raw resources...
I: Copying raw classes.dex file...
I: Copying raw classes2.dex file...
I: Copying raw classes3.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
.apk/classes.dex
Traceback (most recent call last):
  File "deoptfuscator.py", line 18, in <module>
    deobfuscator.main(".apk/"+dex)
  File "deobfuscator/deobfuscator.py", line 9, in main
    ret = opaque_id.opaque_id(dex)
  File "deobfuscator/opaque_id.py", line 6, in opaque_id
    child = subprocess.Popen([os.getenv('ANDROID_HOST_OUT')+'/bin/OTest'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/schni/temp/deoptfuscator/android/bin/OTest'
```

But I can verify that it is there. But if i want to run it manually it also says it couldn't be found. But `cat` works...

![image](https://user-images.githubusercontent.com/9267793/96415476-f679d400-11ee-11eb-94cb-cb066123a23e.png)

**Comment by geunhayou66** [comment]
There is a limitation for file size in managing executable files on github.
So, you should use git-lfs (large file storage) through commands below:

$ curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
$ sudo apt install git-lfs
$ git clone https://github.com/Gyoonus/deoptfuscator.git

**Comment by Gyoonus** [comment]
I believe the issue has been resolved, close the issue.
